# Generated by Django 5.1.5 on 2025-02-07 20:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depotcommun', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='date',
        ),
        migrations.CreateModel(
            name='ShoppingBasket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shopping_baskets', to='depotcommun.customer', verbose_name='Customer')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baskets', to='depotcommun.invoice', verbose_name='Invoice')),
            ],
            options={
                'verbose_name': 'Shopping Basket',
                'verbose_name_plural': 'Shopping Baskets',
            },
        ),
        migrations.AddField(
            model_name='purchase',
            name='basket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='depotcommun.shoppingbasket', verbose_name='Basket'),
        ),
    ]
