# Generated by Django 5.2.7 on 2025-11-04 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depotcommun', '0002_remove_purchase_customer_remove_purchase_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='house_number',
            field=models.CharField(blank=True, max_length=10, verbose_name='House Number'),
        ),
        migrations.AddField(
            model_name='settings',
            name='payment_account_house_number',
            field=models.CharField(blank=True, max_length=10, verbose_name='Account House Number'),
        ),
        migrations.AddField(
            model_name='settings',
            name='payment_account_postal_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='Account Postal Code'),
        ),
    ]
