# Generated by Django 4.0.1 on 2022-01-11 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_bank', models.CharField(blank=True, max_length=50, verbose_name='Bank')),
                ('payment_account_number', models.CharField(blank=True, max_length=50, verbose_name='Kontonummer')),
                ('payment_account_name', models.CharField(blank=True, max_length=100, verbose_name='Kontoname')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
