# Generated by Django 5.0.3 on 2024-03-09 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_invoice_paid_invoice_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='payment_account_place',
            field=models.CharField(blank=True, max_length=100, verbose_name='Account Place'),
        ),
        migrations.AddField(
            model_name='settings',
            name='payment_account_street',
            field=models.CharField(blank=True, max_length=100, verbose_name='Account Street'),
        ),
    ]
