# Generated by Django 5.0.3 on 2024-04-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_settings_payment_account_place_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='zip',
            field=models.CharField(max_length=10, verbose_name='ZIP'),
        ),
    ]
