# Generated by Django 5.0.3 on 2024-04-02 11:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_customer_zip'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Gestartet')),
                ('finished', models.DateTimeField(blank=True, null=True, verbose_name='Beendet')),
                ('log_text', models.TextField(verbose_name='Log')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='email_sent',
            field=models.BooleanField(default=False, verbose_name='Email gesendet'),
        ),
    ]
