# Generated by Django 5.0.3 on 2024-04-02 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_emailtask_invoice_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtask',
            name='successful',
            field=models.BooleanField(default=False, verbose_name='Erfolgreich'),
        ),
    ]
