# Generated by Django 5.0.3 on 2024-04-02 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_emailtask_successful'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtask',
            name='email_count',
            field=models.IntegerField(default=0, verbose_name='Anzahl E-Mails'),
        ),
    ]
