# Generated by Django 5.1.5 on 2025-10-03 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_emailtask_email_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='house_number',
            field=models.CharField(blank=True, max_length=10, verbose_name='House Number'),
        ),
        migrations.AddField(
            model_name='settings',
            name='payment_account_house_number',
            field=models.CharField(blank=True, max_length=10, verbose_name='Account House Number'),
        ),
        migrations.AddField(
            model_name='settings',
            name='payment_account_postal_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='Account Postal Code'),
        ),
    ]
