# Generated by Django 5.2.7 on 2026-04-24 13:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_customer_house_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingBasket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shopping_baskets', to='store.customer', verbose_name='Customer')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baskets', to='store.invoice', verbose_name='Invoice')),
            ],
            options={
                'verbose_name': 'Shopping Basket',
                'verbose_name_plural': 'Shopping Baskets',
            },
        ),
        migrations.AddField(
            model_name='purchase',
            name='basket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='store.shoppingbasket', verbose_name='Basket'),
        ),
    ]
