# Generated by Django 5.2.7 on 2026-05-14 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_shoppingbasket_purchase_basket'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingbasket',
            name='finished',
            field=models.DateTimeField(blank=True, help_text='When the basket was completed', null=True, verbose_name='Finished'),
        ),
    ]
