# Generated by Django 3.1.3 on 2020-11-23 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buying', '0002_auto_20201123_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='depots',
        ),
        migrations.AddField(
            model_name='depot',
            name='users',
            field=models.ManyToManyField(related_name='depots', to='buying.Depot'),
        ),
    ]
