# Generated by Django 3.1.3 on 2020-11-24 14:52

import buying.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buying', '0005_auto_20201123_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='depot',
            name='sign_up_secret',
            field=models.CharField(default=buying.models.make_uuid, max_length=6),
        ),
    ]
