# Generated by Django 3.1.6 on 2021-02-27 16:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buying', '0006_depot_sign_up_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depot',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='items', to='buying.Tag'),
        ),
    ]
