# Generated by Django 3.1.7 on 2021-11-05 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('buying', '0007_auto_20210227_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='depot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='buying.depot'),
        ),
        migrations.AlterField(
            model_name='depot',
            name='users',
            field=models.ManyToManyField(related_name='depots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='itempurchase',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='buying.depot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='purchase',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='buying.invoice'),
        ),
    ]
