# Generated by Django 3.1.7 on 2021-10-31 15:36

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('buying', '0008_auto_20211031_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='depot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='buying.depot'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 31, 15, 36, 35, 870776, tzinfo=utc)),
        ),
    ]
